name: Build and deploy ASP.Net Core app to Azure Web App - nscc-0292233-tickethub

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Restore dependencies
        run: dotnet restore TicketHub/TicketHubapi.csproj

      - name: Build project
        run: dotnet build TicketHub/TicketHubapi.csproj --configuration Release

      - name: Publish project
        run: dotnet publish TicketHub/TicketHubapi.csproj --configuration Release --output ./out

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: dotnet-app
          path: ./out

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read
  
    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: dotnet-app
          path: ./out
  
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2B6ACED9953643CD8A97BCEEA4A0C814 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_50CED2F444F34235AD78569B98478513 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_6C35170CDD8B40DF95CCC4B3CBD79DA6 }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'nscc-0292233-tickethub'
          slot-name: 'Production'
          package: ./out
